# Generated by Django 5.2.1 on 2025-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_description_en',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_description_ru',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_description_en',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_description_ru',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storereview',
            name='review_text_store_en',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='storereview',
            name='review_text_store_ru',
            field=models.TextField(max_length=750, null=True),
        ),
    ]
